// apps/react/pages/index/+Page.tsx
import { useState } from 'react';
import { useMetadata } from 'src';

export default function Page() {
  const [state, setState] = useState(0);

  useMetadata({
    description: 'Home page description',
    keywords: ['Home', 'Page'],
  });

  return (
    <>
      <div>
        <h1>HOME</h1>
        <button onClick={() => setState(state + 1)}>Increment {state}</button>
      </div>
    </>
  );
}

// apps/vue/pages/index/+Page.vue
<template>
  <div>
    <h1>HOME</h1>
    <button type="button" @click="state.count++">Increment {{ state.count }}</button>
  </div>
</template>

<script setup lang="ts">
import { useMetadata } from 'src/index';
import { reactive } from 'vue';

const state = reactive({ count: 0 });

useMetadata({
  description: 'Home page description',
  keywords: ['Home', 'Page'],
});
</script>
