// apps/vue/pages/index/+Page.vue
<template>
  <div>
    <h1>HOME</h1>
    <button type="button" @click="state.count++">Increment {{ state.count }}</button>
  </div>
</template>

<script setup lang="ts">
import { useMetadata } from 'src/index';
import { reactive } from 'vue';

const state = reactive({ count: 0 });

useMetadata({
  description: 'Home page description',
  keywords: ['Home', 'Page'],
});
</script>

// packages/solid/dev/pages/index/+Page.tsx
import { createSignal } from 'solid-js';
import { useMetadata } from 'src/index';

export default function Page() {
  const [signal, setSignal] = createSignal(0);

  useMetadata({
    description: 'Home page description',
    keywords: ['Home', 'Page'],
  });

  return (
    <>
      <div>
        <h1>HOME</h1>
        <button onClick={() => createSignal(signal() + 1)}>Increment {signal()}</button>
      </div>
    </>
  );
}
