// apps/vue/pages/nossr/+Page.vue
<template>
  <div>
    <h1>NO SSR</h1>
    <button type="button" @click="state.count++">Increment {{ state.count }}</button>
  </div>
</template>

<script setup lang="ts">
import { reactive } from 'vue';
import { useMetadata } from 'src';

const state = reactive({ count: 0 });

useMetadata({
  title: 'No SSR',
  description: 'No SSR page description',
  keywords: ['No SSR', 'Page'],
});
</script>

// apps/react/pages/nossr/+Page.tsx
import { useState } from 'react';
import { useMetadata } from 'src';

export default function Page() {
  const [state, setState] = useState(0);

  useMetadata({
    title: 'No SSR',
    description: 'No SSR page description',
    keywords: ['No SSR', 'Page'],
  });

  return (
    <div>
      <h1>NO SSR</h1>
      <button onClick={() => setState(state + 1)}>Increment {state}</button>
    </div>
  );
}
